language: cpp

compiler:
 - clang

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y cmake

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
  - cd test
  - ./ngen_displaytests